/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.dartou.lib;

public final class R {
    public static final class attr {
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int behindOffset=0x7f010003;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int behindScrollScale=0x7f010005;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int behindWidth=0x7f010004;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fadeDegree=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fadeEnabled=0x7f01000a;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>left</code></td><td>0</td><td></td></tr>
<tr><td><code>right</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int mode=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int selectorDrawable=0x7f01000d;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int selectorEnabled=0x7f01000c;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int shadowDrawable=0x7f010008;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int shadowWidth=0x7f010009;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>margin</code></td><td>0</td><td></td></tr>
<tr><td><code>fullscreen</code></td><td>1</td><td></td></tr>
<tr><td><code>none</code></td><td>2</td><td></td></tr>
</table>
         */
        public static int touchModeAbove=0x7f010006;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>margin</code></td><td>0</td><td></td></tr>
<tr><td><code>fullscreen</code></td><td>1</td><td></td></tr>
<tr><td><code>none</code></td><td>2</td><td></td></tr>
</table>
         */
        public static int touchModeBehind=0x7f010007;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int viewAbove=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int viewBehind=0x7f010002;
    }
    public static final class dimen {
        public static int activity_horizontal_margin=0x7f050000;
        public static int activity_vertical_margin=0x7f050001;
        public static int list_padding=0x7f050002;
        public static int shadow_width=0x7f050003;
        public static int slidingmenu_offset=0x7f050004;
    }
    public static final class drawable {
        public static int room_clock=0x7f020000;
        public static int shadow=0x7f020001;
        public static int shadowright=0x7f020002;
    }
    public static final class id {
        public static int content_frame=0x7f040006;
        public static int fullscreen=0x7f040003;
        public static int left=0x7f040000;
        public static int margin=0x7f040002;
        public static int menu_frame=0x7f040007;
        public static int menu_frame_two=0x7f040008;
        public static int none=0x7f040004;
        public static int right=0x7f040001;
        public static int selected_view=0x7f040005;
        public static int slidingmenumain=0x7f040009;
    }
    public static final class integer {
        public static int num_cols=0x7f060000;
    }
    public static final class layout {
        public static int activity_main=0x7f030000;
        public static int content_frame=0x7f030001;
        public static int menu_frame=0x7f030002;
        public static int menu_frame_two=0x7f030003;
        public static int slidingmenumain=0x7f030004;
    }
    public static final class string {
        public static int action_settings=0x7f070000;
        public static int app_name=0x7f070001;
        public static int hello_world=0x7f070002;
    }
    public static final class style {
        /** 
            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static int AppBaseTheme=0x7f080000;
        /**  All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static int AppTheme=0x7f080001;
    }
    public static final class styleable {
        /** Attributes that can be used with a SlidingMenu.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #SlidingMenu_behindOffset com.dartou.lib:behindOffset}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_behindScrollScale com.dartou.lib:behindScrollScale}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_behindWidth com.dartou.lib:behindWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_fadeDegree com.dartou.lib:fadeDegree}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_fadeEnabled com.dartou.lib:fadeEnabled}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_mode com.dartou.lib:mode}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_selectorDrawable com.dartou.lib:selectorDrawable}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_selectorEnabled com.dartou.lib:selectorEnabled}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_shadowDrawable com.dartou.lib:shadowDrawable}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_shadowWidth com.dartou.lib:shadowWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_touchModeAbove com.dartou.lib:touchModeAbove}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_touchModeBehind com.dartou.lib:touchModeBehind}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_viewAbove com.dartou.lib:viewAbove}</code></td><td></td></tr>
           <tr><td><code>{@link #SlidingMenu_viewBehind com.dartou.lib:viewBehind}</code></td><td></td></tr>
           </table>
           @see #SlidingMenu_behindOffset
           @see #SlidingMenu_behindScrollScale
           @see #SlidingMenu_behindWidth
           @see #SlidingMenu_fadeDegree
           @see #SlidingMenu_fadeEnabled
           @see #SlidingMenu_mode
           @see #SlidingMenu_selectorDrawable
           @see #SlidingMenu_selectorEnabled
           @see #SlidingMenu_shadowDrawable
           @see #SlidingMenu_shadowWidth
           @see #SlidingMenu_touchModeAbove
           @see #SlidingMenu_touchModeBehind
           @see #SlidingMenu_viewAbove
           @see #SlidingMenu_viewBehind
         */
        public static final int[] SlidingMenu = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b,
            0x7f01000c, 0x7f01000d
        };
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#behindOffset}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.dartou.lib:behindOffset
        */
        public static final int SlidingMenu_behindOffset = 3;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#behindScrollScale}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.dartou.lib:behindScrollScale
        */
        public static final int SlidingMenu_behindScrollScale = 5;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#behindWidth}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.dartou.lib:behindWidth
        */
        public static final int SlidingMenu_behindWidth = 4;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#fadeDegree}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.dartou.lib:fadeDegree
        */
        public static final int SlidingMenu_fadeDegree = 11;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#fadeEnabled}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.dartou.lib:fadeEnabled
        */
        public static final int SlidingMenu_fadeEnabled = 10;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#mode}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>left</code></td><td>0</td><td></td></tr>
<tr><td><code>right</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.dartou.lib:mode
        */
        public static final int SlidingMenu_mode = 0;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#selectorDrawable}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.dartou.lib:selectorDrawable
        */
        public static final int SlidingMenu_selectorDrawable = 13;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#selectorEnabled}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.dartou.lib:selectorEnabled
        */
        public static final int SlidingMenu_selectorEnabled = 12;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#shadowDrawable}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.dartou.lib:shadowDrawable
        */
        public static final int SlidingMenu_shadowDrawable = 8;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#shadowWidth}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.dartou.lib:shadowWidth
        */
        public static final int SlidingMenu_shadowWidth = 9;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#touchModeAbove}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>margin</code></td><td>0</td><td></td></tr>
<tr><td><code>fullscreen</code></td><td>1</td><td></td></tr>
<tr><td><code>none</code></td><td>2</td><td></td></tr>
</table>
          @attr name com.dartou.lib:touchModeAbove
        */
        public static final int SlidingMenu_touchModeAbove = 6;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#touchModeBehind}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>margin</code></td><td>0</td><td></td></tr>
<tr><td><code>fullscreen</code></td><td>1</td><td></td></tr>
<tr><td><code>none</code></td><td>2</td><td></td></tr>
</table>
          @attr name com.dartou.lib:touchModeBehind
        */
        public static final int SlidingMenu_touchModeBehind = 7;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#viewAbove}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.dartou.lib:viewAbove
        */
        public static final int SlidingMenu_viewAbove = 1;
        /**
          <p>This symbol is the offset where the {@link com.dartou.lib.R.attr#viewBehind}
          attribute's value can be found in the {@link #SlidingMenu} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.dartou.lib:viewBehind
        */
        public static final int SlidingMenu_viewBehind = 2;
    };
}
